### ISSUE TITLE
Excel export

### ISSUE THREAD

**Issue by ward3r** [Mihailorama/SXV#7]
добрый день!
к сожалению, не работает экспорт в эксель: 
![image](https://user-images.githubusercontent.com/22026420/39242734-c1b1ed74-4893-11e8-8a56-ca85891fe0e7.png)
Библиотеку данной версии найти не удалось.

Еще вопрос по исходникам - не смог их найти, везде в архивах только инсталлятор.

**Comment by Mihailorama** [comment]
@ward3r, добрый день! Посмотрим. Спасибо. 
Относительно исходных кодов прошу обращаться admin@xbrl.org.ru

**Comment by Mihailorama** [comment]
Fixed in vers.0.1.2
